[versions]
agp = "8.7.3"
kotlin = "2.1.0"
compose-bom = "2024.12.01"
lifecycle = "2.8.7"
navigation = "2.8.5"
shizuku = "13.1.5"
datastore = "1.1.1"
activity = "1.9.3"
coroutines = "1.8.1"

[libraries]
compose-bom              = { group = "androidx.compose",          name = "compose-bom",                    version.ref = "compose-bom" }
compose-ui               = { group = "androidx.compose.ui",       name = "ui" }
compose-ui-graphics      = { group = "androidx.compose.ui",       name = "ui-graphics" }
compose-ui-tooling       = { group = "androidx.compose.ui",       name = "ui-tooling" }
compose-ui-tooling-prev  = { group = "androidx.compose.ui",       name = "ui-tooling-preview" }
compose-material3        = { group = "androidx.compose.material3", name = "material3" }
compose-icons-extended   = { group = "androidx.compose.material",  name = "material-icons-extended" }
compose-activity         = { group = "androidx.activity",          name = "activity-compose",               version.ref = "activity" }
compose-animation        = { group = "androidx.compose.animation", name = "animation" }

lifecycle-viewmodel      = { group = "androidx.lifecycle",         name = "lifecycle-viewmodel-compose",    version.ref = "lifecycle" }
lifecycle-runtime        = { group = "androidx.lifecycle",         name = "lifecycle-runtime-compose",      version.ref = "lifecycle" }

navigation-compose       = { group = "androidx.navigation",        name = "navigation-compose",             version.ref = "navigation" }

shizuku-api              = { group = "dev.rikka.shizuku",          name = "api",                            version.ref = "shizuku" }
shizuku-provider         = { group = "dev.rikka.shizuku",          name = "provider",                       version.ref = "shizuku" }

datastore                = { group = "androidx.datastore",         name = "datastore-preferences",          version.ref = "datastore" }
coroutines               = { group = "org.jetbrains.kotlinx",      name = "kotlinx-coroutines-android",     version.ref = "coroutines" }

[plugins]
android-application      = { id = "com.android.application",            version.ref = "agp" }
kotlin-android           = { id = "org.jetbrains.kotlin.android",       version.ref = "kotlin" }
kotlin-compose           = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
